/// Flutter icons NishHairCustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NishHairCustomIcons
///      fonts:
///       - asset: fonts/NishHairCustomIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class NishHairCustomIcons {
  NishHairCustomIcons._();

  static const _kFontFam = 'NishHairCustomIcons';
  static const _kFontPkg = null;

  static const IconData orders = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shop_all = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData videos = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wishlist = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData about = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData faq = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData my_bag = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
